# Generated by Django 5.0.6 on 2024-07-26 19:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_contactform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='customer_name',
            new_name='customer_fname',
        ),
        migrations.AddField(
            model_name='contactform',
            name='customer_lname',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
    ]
